// app/dashboard/forms/createOrUpdate/components/FormConstants.ts

import {
  User, Mail, Phone, Building, Upload, GraduationCap,
  MapPin, DollarSign, Globe, MessageSquare, Shield,
  CreditCard, BookOpen, FileText
} from 'lucide-react'

export const fieldIcons: Record<string, any> = {
  full_name: User,
  email: Mail,
  phone: Phone,
  university: Building,
  department: BookOpen,
  deepdepartment: GraduationCap,
  degree: GraduationCap,
  degreenum: CreditCard,
  passport: Shield,
  grad_univerBach: Building,
  grad_univermaster: Building,
  address: MapPin,
  nearestPoint: MapPin,
  govern: MapPin,
  by: MapPin,
  fees: DollarSign,
  univerFees: DollarSign,
  kind_fees: DollarSign,
  traker: FileText,
  pages: FileText,
  magazine: BookOpen,
  mushref: User,
  notes: MessageSquare,
  publishResearch: Globe,
  stilal: FileText,
  international: Globe,
  touch: Phone,
  pdf: Upload,
}

export const fieldLabels: Record<string, string> = {
  full_name: "الاسم الكامل",
  email: "البريد الإلكتروني",
  phone: "رقم الهاتف",
  university: "الجامعة",
  department: "القسم",
  deepdepartment: "التخصص التفصيلي",
  degree: "الدرجة العلمية",
  degreenum: "رقم الشهادة",
  passport: "رقم جواز السفر",
  grad_univerBach: "جامعة البكالوريوس",
  grad_univermaster: "جامعة الماجستير",
  address: "العنوان",
  nearestPoint: "أقرب نقطة",
  govern: "المحافظة",
  by: "المحافظة (بواسطة)",
  fees: "الرسوم بالدينار العراقي",
  univerFees: "رسوم الجامعة",
  kind_fees: "اجور الشركة بالدينار العراقي",
  traker: "رقم التتبع",
  pages: "عدد الصفحات",
  magazine: "المجلة",
  mushref: "المشرف",
  notes: "الملاحظات",
  publishResearch: "نشر البحث",
  stilal: "استلال",
  international: "عالمي",
  touch: "تم التواصل",
  submitted: "مُقدَّم",
  approved: "موافق عليه",
  accepted: "مقبول",
  received: "مستلم",
  payoff: "مدفوع",
  pdf: "رفع ملف PDF",
}

export const fieldPlaceholders: Record<string, string> = {
  full_name: "أدخل الاسم الكامل",
  email: "example@email.com",
  phone: "07xxxxxxxxx",
  department: "القسم الدراسي",
  deepdepartment: "التخصص التفصيلي",
  degreenum: "رقم الشهادة",
  passport: "رقم جواز السفر",
  grad_univerBach: "جامعة البكالوريوس",
  grad_univermaster: "جامعة الماجستير",
  address: "العنوان الكامل",
  nearestPoint: "أقرب نقطة دالة",
  fees: "الرسوم بالدينار العراقي",
  univerFees: "رسوم الجامعة",
  kind_fees: "اجور الشركة بالدينار العراقي",
  traker: "رقم التتبع",
  pages: "عدد الصفحات",
  magazine: "اسم المجلة",
  mushref: "اسم المشرف",
  notes: "ملاحظات إضافية",
}

export const FIELD_CATEGORIES = {
  personal: ['full_name', 'email', 'phone', 'passport', 'address', 'nearestPoint', 'govern', 'by'],
  academic: ['university', 'department', 'deepdepartment', 'degree', 'degreenum', 'grad_univerBach', 'grad_univermaster'],
  financial: ['fees', 'univerFees', 'kind_fees'],
  additional: ['traker', 'pages', 'magazine', 'mushref', 'notes'],
  boolean: ['publishResearch', 'stilal', 'international'],
  status: ['touch', 'submitted', 'approved', 'accepted', 'received', 'payoff'],
}